name: Security OWASP dependency check

on:
  workflow_call:
    inputs:
      channel_id:
        description: 'The slack channel ID to send a message on failure. If this is not provided then no message is sent.'
        required: false
        default: 'NO_SLACK'
        type: string
      subproject:
        description: 'For gradle multi module projects, leave blank for single module projects'
        required: false
        default: ''
        type: string
      slack_include_summary:
        description: 'boolean to include a summary of vulnerabilities in the Slack message'
        required: false
        default: true
        type: boolean
      nvd_feed_version:
        description: 'version of the NVD feed to use'
        required: false
        default: '2'
        type: string
      java_version:
        type: string
        required: false
        default: '21'
    secrets:
      HMPPS_SRE_SLACK_BOT_TOKEN:
        description: 'Slack bot token'
        required: false
      HMPPS_OSS_INDEX_USERNAME:
        description: 'Username for OWASP OSS Index analysis'
        required: false
      HMPPS_OSS_INDEX_PASSWORD:
        description: 'Password (API token) for OWASP OSS Index analysis'
        required: false

permissions:
  contents: read
  security-events: write

jobs:
  # This uses the NVD API v2
  security-owasp-check:
    name: Security OWASP dependency check
    runs-on:  ubuntu-latest
    if: github.repository_owner == 'ministryofjustice'
    permissions:  
      security-events: write
      contents: read
      actions: read
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Set up java
      uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
      with:
        distribution: 'temurin'
        java-version: '${{ inputs.java_version }}'
    - name: Run gradle OWASP Dependency Check Analyse
      id: owasp-analyse
      env:
        SUBPROJECT: ${{ inputs.subproject }}
      run: |
        if [[ -n "${SUBPROJECT}" ]]; then
          TASK="${SUBPROJECT}:dependencyCheckAnalyze"
        else
          TASK="dependencyCheckAnalyze"
        fi
        ./gradlew "${TASK}" -Pdatafeed.url='https://ministryofjustice.github.io/hmpps-nvd-cache/nvd_cache'
      continue-on-error: true
    # Extra sanitisation of SARIF files:
    # - remove newlines from rules ID and reduce them to less than 15 characters
    # - reduce newlines from shortDescription and reduce them to less than 100 characters
    # - amalgamate CVSSv3 and CVSSv2 severities and scores to improve coverage
    # - remove newlines from results RuleID and reduce them to less than 15 characters
    - name: Sanitise sarif
      id: sanitise-sarif
      run: |
        jq '
          .runs |= map(
            if (.tool.driver.rules | type) == "array" then
              .tool.driver.rules |= map(
                (if (.id | type) == "string" then
                  .id = ((.id
                    | gsub("[\\r\\n]+"; " ")
                    | gsub("[[:space:]]+"; " ")
                    | gsub("^[[:space:]]+|[[:space:]]+$"; ""))[0:15])
                else . end)
                | (if (.shortDescription.text | type) == "string" then
                    .shortDescription.text = (
                      .shortDescription.text
                      | gsub("[\\r\\n]+"; " ")
                      | gsub("[[:space:]]+"; " ")
                      | gsub("^[[:space:]]+|[[:space:]]+$"; "")
                      | if length > 100 then .[0:96] + "..." else . end
                    )
                  else . end)
                | .properties.cvss_score = (.properties.cvssv3_baseScore // .properties.cvssv3_score // .properties.cvssv2_score // .properties."security-severity")
                | .properties.cvss_severity = (.properties.cvssv3_baseSeverity // .properties.cvssv3_severity // .properties.cvssv2_severity)
              )
            else
              .
            end
            | if (.results | type) == "array" then
                .results |= map(
                  if (.ruleId | type) == "string" then
                    .ruleId = ((.ruleId
                      | gsub("[\\r\\n]+"; " ")
                      | gsub("[[:space:]]+"; " ")
                      | gsub("^[[:space:]]+|[[:space:]]+$"; ""))[0:15])
                  else . end
                )
              else
                .
              end
          )
        ' "${SARIF_FILE}" > "${SARIF_MOD_FILE}"
      env:
        SARIF_FILE: ${{ inputs.subproject == '' && '.' || inputs.subproject }}/build/reports/dependency-check-report.sarif
        SARIF_MOD_FILE: ${{ inputs.subproject == '' && '.' || inputs.subproject }}/build/reports/dependency-check-report-mod.sarif
      
    # Upload Sarif file: this will attempt to upload the sarif file for private/internal repositories as well
    - name: OWASP upload sarif
      id: owasp-upload-sarif
      uses: github/codeql-action/upload-sarif@5595ccaf912efad79be6eef63a5619ff05969be3 # v4.37.6
      with:
        sarif_file: ${{ inputs.subproject == '' && '.' || inputs.subproject }}/build/reports/dependency-check-report-mod.sarif
        category: gradle-owasp-dependency-check
      # don't stop the job even if Github Advanced Security isn't enabled
      continue-on-error: true
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      id: owasp-upload-artifact
      with:
        name: gradle-owasp-dependency-check-${{ inputs.subproject == '' && github.event.repository.name || inputs.subproject }}
        path: ${{ inputs.subproject == '' && '.' || inputs.subproject }}/build/reports/dependency-check-report.html
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      id: owasp-upload-artifact-sarif
      with:
        name: gradle-owasp-dependency-check-${{ inputs.subproject == '' && github.event.repository.name || inputs.subproject }}-orig.json
        path: ${{ inputs.subproject == '' && '.' || inputs.subproject }}/build/reports/dependency-check-report.sarif
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      id: owasp-upload-artifact-mod-sarif
      with:
        name: gradle-owasp-dependency-check-${{ inputs.subproject == '' && github.event.repository.name || inputs.subproject }}-mod.json
        path: ${{ inputs.subproject == '' && '.' || inputs.subproject }}/build/reports/dependency-check-report-mod.sarif
    - name: Prepare OWASP summary
      id: owasp-summary
      env:
        SARIF_MOD_FILE: ${{ inputs.subproject == '' && '.' || inputs.subproject }}/build/reports/dependency-check-report-mod.sarif
      run: |
        formatted_output=$(jq -r '.runs[0].tool.driver.rules[] | [.id, .shortDescription.text, .properties.cvss_score, .properties.cvss_severity] | @tsv' "${SARIF_MOD_FILE}" \
        | awk -F'\t' '{print $1" - "$NF" ("$(NF-1)") - "$2}' \
        | awk '{printf "%s\\n", $0}') 
        echo "Vulnerability Summary"
        echo "====================="
        echo "${formatted_output}" | sed 's/\\n/\n/g'
        slack_summary="$(echo "${formatted_output}" | awk '{s=s $0} END {if (length(s) >= 3000) print substr(s, 1, 2997) "..."; else print s}')"
        echo "summary=${slack_summary}" >> $GITHUB_OUTPUT
    - name: Gradle OWASP slack notification
      uses: ministryofjustice/hmpps-github-shared-actions/.github/actions/slack_codescan_notification@35bb5e74a025299cddf50909c1968444d966c1dc # v1.0.21
      if: (failure() || steps.owasp-analyse.outcome == 'failure') && inputs.channel_id != 'NO_SLACK'
      with:
        title: "Gradle OWASP"
        warningOnly: ${{ steps.owasp-upload-sarif.outcome == 'success' && steps.owasp-upload-artifact.outcome == 'success' }}
        channel_id: ${{ inputs.channel_id}}
        SLACK_BOT_TOKEN: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}
        subproject: ${{ inputs.subproject }}
        summary: ${{ inputs.slack_include_summary && steps.owasp-summary.outputs.summary || '' }}
